import type { Metadata } from 'next'
import { Montserrat_Alternates } from 'next/font/google'
import './globals.css'
import { Providers } from './providers'

const montserrat = Montserrat_Alternates({
	style: 'normal',
	weight: ['300', '500', '600', '700', '900'],
	subsets: ['cyrillic'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={montserrat.className}>
				<Providers>{children}</Providers>
			</body>
		</html>
	)
}
